on: [push, pull_request]

name: Linting

jobs:
  tsLint:
    name: Runs TSLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.2.0
      - run: |
          npm ci
          npm run lint
