on: [push, pull_request]

name: Linting

jobs:
  tsLint:
    name: Runs TSLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.5.1
      - run: |
          npm ci
          npm run lint
