on: [push, pull_request]

name: Linting

jobs:
  tsLint:
    name: Runs TSLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.7.0
      - run: |
          npm ci
          npm run lint
